author = "mos9527"
name = "MegaMix+ Steam Rich Presence"
enabled = true
date = "10.09.2022"
description = """
MM+ Steam Rich Presence 

mos9527,2022\
"""
version = "0.0.1a"
dll = [
"MMSteamRP.dll",
]
